spring:
  config:
    import: optional:configserver://localhost:8761
    zipkin:
      base-url: http://loclahost:9411/
    sleuth:
      sampler:
        probability: 1
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: student-service-db
      host: localhost
      port: 27017
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost