spring:
  application:
    name: gateway-service
    description: API Gateway for School Management App

  config:
    import: optional:configserver://localhost:8761

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8089
          predicates:
            - Path=/users/**

        - id: student-service
          uri: http://localhost:8087
          predicates:
            - Path=/students/**

        - id: teacher-service
          uri: http://localhost:8088
          predicates:
            - Path=/teachers/**

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
