version: '3.8'

services:
  mysql:
    image: mysql:8.0.42-debian
    container_name: school-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"
    networks:
      - school-net

  springboot:
    build: .
    container_name: school-springboot
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - school-net

networks:
  school-net:
