spring:
  application:
    name: configuration-service
    description:



  # data:
  #   mongodb:
  #     uri: "mongodb://localhost:27017"
  #     database: configuration-service-db
  #     host: localhost
  #     port: 27017
server:
  port: 8082


